// ActionTypes for the products
export const PRODUCTS_ADD_PRODUCT = "PRODUCTS_ADD_PRODUCT";
export const PRODUCTS_DELETE_PRODUCT = "PRODUCTS_DELETE_PRODUCT";
export const PRODUCTS_UPDATE_PRODUCT = "PRODUCTS_UPDATE_PRODUCT";
export const PRODUCTS_GET_PRODUCTS = "PRODUCTS_GET_PRODUCTS";

// Otros ActionTypes para diferentes funcionalidades
export const FETCH_DATA_REQUEST = "FETCH_DATA_REQUEST";
export const FETCH_DATA_SUCCESS = "FETCH_DATA_SUCCESS";
export const FETCH_DATA_FAILURE = "FETCH_DATA_FAILURE";
